name: SolorideApp

services:
    api:
        image: ${DOCKER_REGISTRY-}soloride-api
        container_name: soloride-api
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=8080 
        ports:
            - 7100:8080
        depends_on:
            - postgres
            - redis
            - rabbitmq
    postgres:
        image: postgres:17-alpine
        container_name: soloride-db
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - "5532:5432"
        volumes:
            - soloride-db-data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: soloride_adminer
        restart: unless-stopped
        ports: 
            - "8080:8080"
    
    redis:
        image: redis:7-alpine
        container_name: soloride-redis
        restart: unless-stopped
        command: ["redis-server", "--appendonly", "yes"]
        ports: 
            - "6379:6379"
        volumes:
            - redis-data:/data
    
    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: soloride-rabbitmq
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=soloride
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - "5672:5672"
            - "15672:15672" 

volumes:
    soloride-db-data:
    redis-data:
