name: RidelyApp

services:
    api:
        image: ${DOCKER_REGISTRY-}ridely-api
        container_name: ridely-api
        build:
            context: .
            dockerfile: src/Ridley.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=8080 
        ports:
            - 7900:8080
        depends_on:
            - postgres
            - redis
            - rabbitmq
    postgres:
        image: postgres:17-alpine
        container_name: ridely-db
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - "5932:5432"
        volumes:
            - ridely-db-data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: ridely_adminer
        restart: unless-stopped
        ports: 
            - "8080:8080"
    
    redis:
        image: redis:7-alpine
        container_name: ridely-redis
        restart: unless-stopped
        command: ["redis-server", "--appendonly", "yes"]
        ports: 
            - "6379:6379"
        volumes:
            - redis-data:/data
    
    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: ridely-rabbitmq
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=ridely
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - "5672:5672"
            - "15672:15672" 

volumes:
    ridely-db-data:
    redis-data:
